<?php
// $array_list=array(
// "Accesorios",
// "Almacenamiento",
// "Computadoras",
// "MAC",
// "Electrónica",
// "Hardware",
// "Impresión",
// "Redes",
// "Servidores",
// "Software",
// "Gaming",
// );

# ACCESORIOS
$array_list=array(
"Mochilas y Maletines",
"Bocinas",
"Mouse / Ratones",
"Teclados",
"Pilas, Baterías y Cargadores",
"Limpieza",
"Cables de Video",
"Audífonos y Micrófonos",
"Cables USB",
"Cables de Red",
"Mouse Pads",
"Herramientas",
"Accesorios para Celular",
"Joysticks y Joypads",
"Adaptadores de Corriente",
"Cámaras Web",
"Cables Internos",
"Lectores de Memoria Flash",
"Bases para Laptops",
"Apuntadores Láser",
"Candados de Seguridad",
"Tabletas Gráficas Digitales",
"Soportes para TV",
"Cables de Audio",
"Accesorios para iPad y Tablets",
"Cables de Energía",
"Antenas",
"Accesorios para Proyector",
"Filtros de Privacidad",
"Calculadoras",
);
?>